### ISSUE TITLE
Server Side Include Injection Not Working

### ISSUE THREAD

**Issue by Sybrid203** [raesene/bWAPP#10]
There's no ssii.shtml file to be found on bwapp, making the SSI directive on the .php page irrelevant.
What? 
Did someone else encounter this issue? Everybody is happy and all solving that challenge on Youtube videos, but here I am - STUCK, and for no apparent reason.
Tried downloading older versions looking for that shtml file, but... nope! Guess I would have to create one myself, which should be of no problem, but shouldn't these learning platforms be plug & hack? 
The bWAPP instance is running as a container which is being managed through Portainer. 
Thank you!

**Comment by hulk510** [comment]
hi @Sybrid203 
This issue is closed, but it didn't work for me as well.
I've figured out how to fix it, so I'll write it down.
I don't know if I'm right...

1. check apache2 error.log
```
cat /var/logs/apache2
```
and check fopen error, In my case, it was "permission denied". (So I don't know if it's anything other than this. sorry..)
```
[Fri Jul 16 15:04:13.393267 2021] [:error] [pid 1219] [client 10.0.0.1:55304] PHP Warning:  fopen(ssii.shtml): failed to open stream: Permission denied in /app/ssii.php on line 77, referer: http://localhost:8890/ssii.php
```
2. check permission

my permission was "root root"
```
-rw-r--r-- 1 root root  6546 Jul  9 17:08 ssii.php
```

3. change permission to apache2 user

I looked up apache2 user in /etc/passwd.
maybe www-data.
```
chown -R www-data:www-data /var/www/html/
```
I got it working with this change!

I'm happy to help you :)

ps.
I was able to display it. But it didn't work. Maybe it doesn't work because it says "bee-box only".
